const PRODUCT_PLACEHOLDER_IMAGE = "img/products/product-placeholder.svg";

function product({
  id,
  nombre,
  precio,
  categoria,
  marca,
  presentacion = "",
  sabores = [],
  objetivos = [],
  disponible = true,
  destacado = false,
  imagen = PRODUCT_PLACEHOLDER_IMAGE,
  imagenPendiente = imagen === PRODUCT_PLACEHOLDER_IMAGE,
  subtitulo,
  beneficios,
  descripcion,
  uso,
}) {
  const flavorText = sabores.length ? ` Sabores disponibles: ${sabores.join(", ")}.` : "";
  const goalText = objetivos.length ? ` Ideal para: ${objetivos.join(", ")}.` : "";

  return {
    id,
    nombre,
    subtitulo: subtitulo || `${categoria}${presentacion ? ` ${presentacion}` : ""}.${goalText}`,
    precio,
    categoria,
    marca,
    presentacion,
    sabores,
    objetivos,
    disponible,
    destacado,
    tag: disponible ? "Disponible" : "Consultar stock",
    imagen,
    imagenPendiente,
    alt: nombre,
    whatsappMensaje: `Hola Javy, quiero asesoría sobre ${nombre}.`,
    beneficios: beneficios || [
      objetivos.length ? `Apoya objetivos de ${objetivos.join(", ").toLowerCase()}.` : "Apoya tu rutina de suplementación.",
      "Producto agregado desde el catálogo disponible.",
      "Javy puede orientarte sobre uso, sabor y disponibilidad.",
    ],
    descripcion: descripcion || [
      `${nombre} es un producto de ${marca} dentro de la categoría ${categoria.toLowerCase()}.`,
      `Precio de catálogo: $${Number(precio).toFixed(2)}.${flavorText}`,
    ],
    uso: uso || [
      "Consultar la dosis indicada en la etiqueta del producto.",
      "Usar como complemento de una alimentación y entrenamiento adecuados.",
      "Si tienes condiciones médicas o sensibilidad a estimulantes, consulta antes de usar.",
    ],
  };
}

const PRODUCT_LIST = [
  product({ id: "amino-energy-30-serv", nombre: "Amino Energy", precio: 34, categoria: "Amino+energía", marca: "Optimum Nutrition", presentacion: "270 gr - 30 servidas", sabores: ["Blue Raspberry","Fruit Fusion","Sandía","Uva","Blueberry Mojito","Strawberry Lime","Orange","Green Apple"], objetivos: ["Energía y enfoque","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "amino-energy-varios-sabores", nombre: "Amino Energy", precio: 25, categoria: "Aminoácidos", marca: "Optimum Nutrition", sabores: ["Blue Raspberry","Fresa Lima","Fruit Fusion","Green Apple","Mojito","Naranja","Sandía","Uva"], objetivos: ["Energía y enfoque","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-bcaa", nombre: "Nutrex BCAA", precio: 15, categoria: "Aminoácidos", marca: "Nutrex", sabores: ["Fruit Punch","Green Apple","Watermelon"], objetivos: ["Fuerza y rendimiento","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-eaa", nombre: "Nutrex EAA", precio: 25, categoria: "Aminoácidos", marca: "Nutrex", sabores: ["Fresa Sandía","Limón y Lima","Manzana","Naranja"], objetivos: ["Fuerza y rendimiento","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "skull-bcaa-eaa", nombre: "Skull BCAA + EAA", precio: 20, categoria: "Aminoácidos", marca: "Skull", objetivos: ["Fuerza y rendimiento","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "xtend-bcaa-30-serv", nombre: "Xtend BCAA 30 servidas", precio: 25, categoria: "Aminoácidos", marca: "Xtend", sabores: ["Fruit Punch","Glacial Grape","Mango Madness"], objetivos: ["Fuerza y rendimiento","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "cbum-energy-drink-355ml", nombre: "CBUM Energy Drink 355 ml", precio: 2.5, categoria: "Bebidas", marca: "CBUM", presentacion: "355 ml", sabores: ["Blue Snow Cone","Blueberry Lemonade","Citrus Burst","Orange Sunrise","Peach Mango","Pink Lemonade","Piña Colada"], objetivos: ["Energía y enfoque"], imagen: "img/products/cbum-energy-drink-355ml.webp" }),
  product({ id: "biotin-vitamin-b7-120-caps", nombre: "Biotin Vitamin B7 120 cápsulas", precio: 15, categoria: "Belleza", marca: "Biotin", presentacion: "120 cápsulas", objetivos: ["Belleza"] }),
  product({ id: "mutant-caffeine-240-tabs", nombre: "Mutant Caffeine 240 tabletas", precio: 12.5, categoria: "Cafeína", marca: "Mutant", presentacion: "240 tabletas", objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "maltodextrin-2lb", nombre: "Maltodextrin 2 lb", precio: 20, categoria: "Carbohidratos", marca: "Maltodextrin", presentacion: "2 lb / 60 servidas", objetivos: ["Energía y enfoque","Ganar masa"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "maltodextrin-8lb", nombre: "Maltodextrin 8 lb", precio: 45, categoria: "Carbohidratos", marca: "Maltodextrin", presentacion: "8 lb / 242 servidas", objetivos: ["Energía y enfoque","Ganar masa"] }),
  product({ id: "nutricost-casein-5lb", nombre: "Nutricost Casein", precio: 75, categoria: "Caseína", marca: "Nutricost", presentacion: "5 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "nutricost-casein-2lb", nombre: "Nutricost Casein 2 lb", precio: 38, categoria: "Caseína", marca: "Nutricost", presentacion: "2 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "bpi-creatine-max-60-serv", nombre: "BPI Creatine Max 60 servidas", precio: 11.5, categoria: "Creatina", marca: "BPI Sports", presentacion: "60 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "muscletech-cell-tech-3lb", nombre: "MuscleTech Cell-Tech 3 lb", precio: 34, categoria: "Creatina", marca: "MuscleTech", presentacion: "3 lb", sabores: ["Fruit Punch"], objetivos: ["Fuerza y rendimiento","Ganar masa"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "muscletech-cell-tech-6lb", nombre: "MuscleTech Cell-Tech 6 lb", precio: 47, categoria: "Creatina", marca: "MuscleTech", presentacion: "6 lb", sabores: ["Fruit Punch"], objetivos: ["Fuerza y rendimiento","Ganar masa"], imagen: "img/products/muscletech-cell-tech-6lb.webp" }),
  product({ id: "nutrex-creatine-flavored-60-serv", nombre: "Nutrex Creatine 60 servidas saborizada", precio: 18, categoria: "Creatina", marca: "Nutrex", presentacion: "60 servidas", sabores: ["Fresa Sandía","Fruit Punch","Mango"], objetivos: ["Fuerza y rendimiento"], imagen: "img/products/nutrex-creatine-flavored-60-serv.webp", destacado: true }),
  product({ id: "nutrex-creatine-200-serv", nombre: "Nutrex Creatine Monohydrate 200 servidas", precio: 33.5, categoria: "Creatina", marca: "Nutrex", presentacion: "200 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/nutrex-creatine-200-serv.webp" }),
  product({ id: "nutrex-creatine-60-serv", nombre: "Nutrex Creatine Monohydrate 60 servidas", precio: 15, categoria: "Creatina", marca: "Nutrex", presentacion: "60 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/nutrex-creatine-60-serv.webp", destacado: true }),
  product({ id: "nutricost-creatine-flavored-45-serv", nombre: "Nutricost Creatine 45 servidas saborizada", precio: 15, categoria: "Creatina", marca: "Nutricost", presentacion: "45 servidas", sabores: ["Berry Blast","Fruit Punch","Mandarina Naranja","Uva"], objetivos: ["Fuerza y rendimiento"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "olympus-creatine-100-serv", nombre: "Olympus Creatine 100 servidas", precio: 16.5, categoria: "Creatina", marca: "Olympus", presentacion: "100 servidas", objetivos: ["Fuerza y rendimiento"] }),
  product({ id: "olympus-creatine-60-serv", nombre: "Olympus Creatine 60 servidas", precio: 10.5, categoria: "Creatina", marca: "Olympus", presentacion: "60 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "bsn-aminox-eaas-375-gr-25-servidas", nombre: "Aminox EAAs", precio: 20, categoria: "EAA", marca: "BSN", presentacion: "375 gr - 25 servidas", sabores: ["Watermelon"] }),
  product({ id: "primaforce-eaa-30-serv", nombre: "Primaforce EAA 30 servidas", precio: 16.5, categoria: "EAA", marca: "Primaforce", presentacion: "30 Servidas", sabores: ["Tropical Fruit Punch"], objetivos: ["Fuerza y rendimiento","Recuperación"] }),
  product({ id: "nutrex-glutamine-300g", nombre: "Nutrex Glutamine 300 g", precio: 15, categoria: "Glutamina", marca: "Nutrex", presentacion: "60 servidas", objetivos: ["Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "biosport-absolute-iso-4lb", nombre: "Absolute ISO", precio: 65, categoria: "ISO (aislada)", marca: "Biosport", presentacion: "4 lb", sabores: ["Chocolate","Cookies","Vainilla"], objetivos: ["Definición","Recuperación"], imagen: "img/products/biosport-absolute-iso-4lb.webp" }),
  product({ id: "carnivor-iso-2lb", nombre: "Carnivor Beef ISO Protein", precio: 38.5, categoria: "ISO (aislada)", marca: "MuscleMeds", presentacion: "2 lb - 28 servidas", sabores: ["Chocolate Peanut Butter","Cookies","Vainilla","Caramelo"], objetivos: ["Definición","Recuperación"], imagen: "img/products/carnivor-iso-2lb.webp" }),
  product({ id: "carnivor-iso-4lb", nombre: "Carnivor ISO 4 lb", precio: 63, categoria: "ISO (aislada)", marca: "MuscleMeds", presentacion: "4 lb - 56 servidas", sabores: ["Chocolate","Chocolate Maní","Cookies","Fresa","Vainilla","Caramelo"], objetivos: ["Definición","Recuperación"], imagen: "img/products/carnivor-iso-4lb.webp" }),
  product({ id: "dymatize-iso-100-hidrolyzed-20-servidas", nombre: "ISO 100 HIDROLYZED", precio: 40, categoria: "ISO (aislada)", marca: "Dymatize", presentacion: "20 servidas", sabores: ["Chocolate gourmet","cookies","brownie","choco peanut","fresa","vainilla","dunkin glazed donut","dunkin mocha latte"], objetivos: ["Definición","Fuerza y rendimiento","Ganar masa"] }),
  product({ id: "mutant-iso-surge-1-6-lb-23-servidas", nombre: "Iso Surge", precio: 36, categoria: "ISO (aislada)", marca: "Mutant", presentacion: "1.6 lb - 23 servidas", sabores: ["Peanut Butter Chocolate","Fresa","Cookies","Triple Chocolate"] }),
  product({ id: "mutant-iso-surge-5lb", nombre: "ISO Surge 5 lb", precio: 74, categoria: "ISO (aislada)", marca: "Mutant", presentacion: "5 lb", sabores: ["Triple Chocolate","Vainilla","Cookies and Cream","Fresa Milkshake"], objetivos: ["Definición","Recuperación"], imagen: "img/products/mutant-iso-surge-5lb.webp" }),
  product({ id: "nutrex-isofit-protein-2lb", nombre: "Isofit Protein", precio: 40, categoria: "ISO (aislada)", marca: "Nutrex", presentacion: "2.3 lb - 30 servidas", sabores: ["Banana","Chocolate","Cookies"], objetivos: ["Definición","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-isofit-protein-5lb", nombre: "Isofit Protein", precio: 75, categoria: "ISO (aislada)", marca: "Nutrex", presentacion: "5 lb - 70 servidas", sabores: ["Chocolate shake","Cookies and Cream","Fresa and Cream"], objetivos: ["Definición","Recuperación"], imagen: "img/products/nutrex-isofit-protein-5lb.webp" }),
  product({ id: "isomorph-28g-protein", nombre: "Isomorph 28 Pure Whey Isolate", precio: 36, categoria: "ISO (aislada)", marca: "APS Nutrition", presentacion: "2 lb - 27 servidas", sabores: ["Chocolate","Cookies","Fresa","Honey Granola","Vainilla"], objetivos: ["Definición","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "htp-precision-protein", nombre: "Precision Protein", precio: 36, categoria: "ISO (aislada)", marca: "HTP", presentacion: "2 lb - 28 servidas", sabores: ["Chocolate","Chocolate Peanut Butter","Cookies","Fresa","Honey Granola","Vainilla"], objetivos: ["Definición","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "raw-grass-fed-isolate-2lb", nombre: "RAW Grass Fed Isolate Protein 2 lb", precio: 45, categoria: "ISO (aislada)", marca: "RAW Nutrition", presentacion: "2 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Definición","Recuperación"], imagen: "img/products/raw-grass-fed-isolate-2lb.webp" }),
  product({ id: "isopure-zero-carb-protein-4-5-lb", nombre: "Zero Carb Protein", precio: 40, categoria: "ISO (aislada)", marca: "Isopure", presentacion: "4.5 lb", sabores: ["Vainilla"], objetivos: ["Definición","Recuperación"] }),
  product({ id: "biosport-xtreme-gainer-3kg", nombre: "BioSport Xtreme Gainer", precio: 35, categoria: "Mass gainer", marca: "BioSport USA", presentacion: "3 kg / 6.6 lb", sabores: ["Chocolate","Cookies & Cream","Fresa","Vainilla"], objetivos: ["Ganar masa"], imagen: "img/products/biosport-xtreme-gainer-3kg.webp" }),
  product({ id: "brutal-mass-15lb", nombre: "Brutal Mass Gainer 15 lb", precio: 60, categoria: "Mass gainer", marca: "Terror Labz", presentacion: "15 lb", sabores: ["Chocolate","Cookies","Vainilla"], objetivos: ["Ganar masa"], imagen: "img/products/brutal-mass-15lb.webp" }),
  product({ id: "brutal-mass-7-5lb", nombre: "Brutal Mass Gainer 7.5 lb", precio: 33.5, categoria: "Mass gainer", marca: "Terror Labz", presentacion: "7.5 lb", sabores: ["Chocolate","Cookies"], objetivos: ["Ganar masa"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "muntant-mass-extreme-2500-6-lb", nombre: "Mass Extreme 2500", precio: 30, categoria: "Mass gainer", marca: "Mutant", presentacion: "6 lb", sabores: ["Chocolate","Vainilla","Galleta"], objetivos: ["Fuerza y rendimiento","Ganar masa"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "mutant-mass-extreme-2500-15lb", nombre: "Mass Extreme 2500", precio: 40, categoria: "Mass gainer", marca: "Mutant", presentacion: "15 lb", sabores: ["galleta","chocolate"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "nutrex-mass-infusion-12lb", nombre: "Mass Infusion 12 lb", precio: 62, categoria: "Mass gainer", marca: "Nutrex", presentacion: "12 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Ganar masa"], imagen: "img/products/nutrex-mass-infusion-12lb.webp" }),
  product({ id: "carnivor-mass-6lb", nombre: "MuscleMeds Carnivor Mass 6 lb", precio: 47, categoria: "Mass gainer", marca: "MuscleMeds", presentacion: "6 lb", sabores: ["Chocolate","Chocolate Peanut Butter","Vainilla"], objetivos: ["Ganar masa"], imagen: "img/products/carnivor-mass-6lb.webp" }),
  product({ id: "optimun-nutrition-serious-mass-6-lb", nombre: "Serious Mass", precio: 60, categoria: "Mass gainer", marca: "Optimun Nutrition", presentacion: "6 lb", sabores: ["Vainilla","Chocolate"], objetivos: ["Ganar masa"] }),
  product({ id: "optimum-nutrition-serious-mass-12lb", nombre: "Serious Mass 12 lb", precio: 62, categoria: "Mass gainer", marca: "Optimum Nutrition", presentacion: "12 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Ganar masa"], imagen: "img/products/optimum-nutrition-serious-mass-12lb.webp" }),
  product({ id: "mutant-multivitamin-60-tabs", nombre: "Mutant Multivitamin 60 tabletas", precio: 14, categoria: "Multivitamínicos", marca: "Mutant", presentacion: "60 tabletas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-vitadapt", nombre: "Nutrex Vitadapt", precio: 19, categoria: "Multivitamínicos", marca: "Nutrex", objetivos: ["Energía y enfoque","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "biosport-omega-3-60-caps", nombre: "Biosport Omega 3 60 cápsulas", precio: 9, categoria: "Omega", marca: "Biosport", presentacion: "60 cápsulas", objetivos: ["Salud general"] }),
  product({ id: "nutrex-t-up-max-60-caps", nombre: "Nutrex T-UP Max 60 cápsulas", precio: 20, categoria: "Potenciadores hormonales", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Fuerza y rendimiento","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-tribulus-90-caps", nombre: "Nutrex Tribulus 90 cápsulas", precio: 15, categoria: "Potenciadores hormonales", marca: "Nutrex", presentacion: "90 cápsulas", objetivos: ["Fuerza y rendimiento","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "tongkat-ali-complex-1000mg", nombre: "Tongkat Ali Complex 1000 mg 60 cápsulas", precio: 15.5, categoria: "Potenciadores hormonales", marca: "Tongkat Ali", presentacion: "60 cápsulas", objetivos: ["Fuerza y rendimiento","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "adiplex-kiwi-berry", nombre: "Adiplex", precio: 13.5, categoria: "Pre-entrenos y energía", marca: "Adiplex", sabores: ["Kiwi-Berry"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "maniac-extreme-preworkout", nombre: "Maniac Extreme Pre-Workout", precio: 25, categoria: "Pre-entrenos y energía", marca: "Maniac", sabores: ["Green Apple","Watermelon"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "mesomorph-pre-workout", nombre: "Mesomorph Pre-Workout", precio: 10, categoria: "Pre-entrenos y energía", marca: "APS Nutrition", sabores: ["Varios sabores"], objetivos: ["Energía y enfoque","Fuerza y rendimiento"], imagen: "img/products/mesomorph-pre-workout.webp", destacado: true }),
  product({ id: "nutrex-outrage", nombre: "Nutrex Outrage", precio: 22, categoria: "Pre-entrenos y energía", marca: "Nutrex", sabores: ["Blue Raspberry","Fruit Punch","Lemon Lime"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "primaforce-beta-alanine-100-serv", nombre: "Primaforce Beta-Alanine 100 servidas", precio: 15, categoria: "Pre-entrenos y energía", marca: "Primaforce", presentacion: "100 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "hyde-nightmare", nombre: "ProSupps Hyde Nightmare", precio: 27.5, categoria: "Pre-entrenos y energía", marca: "ProSupps", sabores: ["Jawbreaker"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "hyde-nightmare-intense-energy", nombre: "ProSupps Hyde Nightmare Intense Energy", precio: 27.5, categoria: "Pre-entrenos y energía", marca: "ProSupps", sabores: ["Blood Berry"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg", disponible: false }),
  product({ id: "raw-cbum-essential-30-serv", nombre: "RAW Nutrition CBUM Essential 30 servidas", precio: 24, categoria: "Pre-entrenos y energía", marca: "RAW Nutrition", sabores: ["Blue Raspberry","Citrus Grapefruit","Fruit Burst","Orange","Peach Mango","Sour Watermelon"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "skull-preworkout-xtreme", nombre: "Skull Pre-Workout Xtreme", precio: 20, categoria: "Pre-entrenos y energía", marca: "Skull", sabores: ["Sour Apple Rage"], objetivos: ["Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "creatina-nutrex-60", nombre: "Producto sin nombre", precio: 15.99, categoria: "Producto", marca: "Nutrex", presentacion: "60 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/creatine-nutrex-60srv.webp", disponible: false }),
  product({ id: "carniburn-fuego", nombre: "Carniburn Fuego", precio: 35, categoria: "Quemadores", marca: "Carniburn", sabores: ["Sour Gummie","Strawberry Watermelon"], objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "h2o-diuretico", nombre: "H2O Diurético", precio: 18, categoria: "Quemadores", marca: "H2O", sabores: ["kkk"], objetivos: ["Definición"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "liquid-l-carnitine", nombre: "L-Carnitine Líquida", precio: 18, categoria: "Quemadores", marca: "Nutrex", presentacion: "31 servidas", sabores: ["Berry Blast","Orange Mango","Strawberry Watermelon"], objetivos: ["Definición","Energía y enfoque"] }),
  product({ id: "lipodrene-fat-burner", nombre: "Lipodrene Fat Burner", precio: 33, categoria: "Quemadores", marca: "Hi-Tech Pharmaceuticals", sabores: ["Amarillo","Hardcore","Xtreme"], objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-lipo-6-black-60-caps", nombre: "Nutrex Lipo-6 Black 60 cápsulas", precio: 20, categoria: "Quemadores", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/nutrex-lipo-6-black-60-caps.webp", destacado: true }),
  product({ id: "nutrex-lipo-6-hardcore-60-caps", nombre: "Nutrex Lipo-6 Hardcore 60 cápsulas", precio: 22, categoria: "Quemadores", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-lipo-6-hers-60-caps", nombre: "Nutrex Lipo-6 Hers 60 cápsulas", precio: 20, categoria: "Quemadores", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-lipo-6-intense-60-caps", nombre: "Nutrex Lipo-6 Intense 60 cápsulas", precio: 22, categoria: "Quemadores", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Definición","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-lipo-6-stim-free-60-caps", nombre: "Nutrex Lipo-6 Stim-Free 60 cápsulas", precio: 20, categoria: "Quemadores", marca: "Nutrex", presentacion: "60 cápsulas", objetivos: ["Definición"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "xpel-diuretico", nombre: "Xpel Diurético", precio: 18, categoria: "Quemadores", marca: "Xpel", objetivos: ["Definición"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "muscletech-platinum-creatine-400g", nombre: "Platinum Creatine Monohydrate", precio: 28, categoria: "Saborizada", marca: "MuscleTech", presentacion: "400 g - 60 servidas", sabores: ["Berry"], objetivos: ["Fuerza y rendimiento"] }),
  product({ id: "ashwagandha-90-caps", nombre: "Ashwagandha 90 cápsulas", precio: 16.5, categoria: "Salud y bienestar", marca: "Ashwagandha", presentacion: "90 cápsulas", objetivos: ["Descanso y estrés","Energía y enfoque"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "biosport-magnesium-glycinate-60-caps", nombre: "Biosport Magnesium Glycinate 60 cápsulas", precio: 10.5, categoria: "Salud y bienestar", marca: "Biosport", presentacion: "60 cápsulas", objetivos: ["Descanso y estrés"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "biotin-women-120-caps", nombre: "Biotin Women 120 cápsulas", precio: 18, categoria: "Salud y bienestar", marca: "Biotin Women", presentacion: "120 cápsulas", objetivos: ["Belleza"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "calcium-vitamin-d-240-caps", nombre: "Calcium + Vitamin D 240 cápsulas", precio: 18, categoria: "Salud y bienestar", marca: "Calcium + Vitamin D", presentacion: "240 cápsulas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "inositol-500mg-240-caps", nombre: "Inositol 500 mg 240 cápsulas", precio: 20, categoria: "Salud y bienestar", marca: "Inositol", presentacion: "240 cápsulas", objetivos: ["Descanso y estrés"] }),
  product({ id: "l-arginine-50-serv", nombre: "L-Arginine", precio: 16.5, categoria: "Salud y bienestar", marca: "Nutricost", presentacion: "50 servidas", objetivos: ["Energía y enfoque","Salud general"] }),
  product({ id: "liv52-protector-hepatico", nombre: "Liv52 Protector Hepático", precio: 15, categoria: "Salud y bienestar", marca: "Liv52", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "mutant-big-greens-30-serv", nombre: "Mutant Big Greens 30 servidas", precio: 20, categoria: "Salud y bienestar", marca: "Mutant", sabores: ["Chocolate"], objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg", disponible: false }),
  product({ id: "nac-1000mg-120-caps", nombre: "NAC 1000 mg 120 cápsulas", precio: 20, categoria: "Salud y bienestar", marca: "nutricost", presentacion: "120 cápsulas", objetivos: ["Salud general"] }),
  product({ id: "nad-plus", nombre: "NAD+", precio: 50, categoria: "Salud y bienestar", marca: "NAD+", objetivos: ["Energía y enfoque","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "olive-leaf-extract-90-caps", nombre: "Olive Leaf Extract 75 mg 90 cápsulas", precio: 25, categoria: "Salud y bienestar", marca: "Olive Leaf", presentacion: "90 cápsulas", objetivos: ["Salud general"] }),
  product({ id: "potassium-99mg-240-caps", nombre: "Potassium 99 mg 240 cápsulas", precio: 20, categoria: "Salud y bienestar", marca: "Potassium", presentacion: "240 cápsulas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "potassium-99mg-30-caps", nombre: "Potassium 99 mg 30 cápsulas", precio: 9.5, categoria: "Salud y bienestar", marca: "Potassium", presentacion: "30 cápsulas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "primaforce-tudca-500mg-30-caps", nombre: "Primaforce TUDCA 500 mg 30 cápsulas", precio: 27.5, categoria: "Salud y bienestar", marca: "Primaforce", presentacion: "30 cápsulas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "r-alpha-lipoic-acid-120-caps", nombre: "R-Alpha Lipoic Acid 120 cápsulas", precio: 25, categoria: "Salud y bienestar", marca: "R-ALA", presentacion: "120 cápsulas", objetivos: ["Definición","Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "resveratrol-120-caps", nombre: "Resveratrol 120 cápsulas", precio: 25.5, categoria: "Salud y bienestar", marca: "Resveratrol", presentacion: "120 cápsulas", objetivos: ["Salud general"] }),
  product({ id: "revive-vitamin-c-200-caps", nombre: "Revive Vitamin C 200 cápsulas", precio: 13.5, categoria: "Salud y bienestar", marca: "Revive", presentacion: "200 cápsulas", objetivos: ["Salud general"] }),
  product({ id: "vitamin-c-500mg-240-caps", nombre: "Vitamin C 500 mg 240 cápsulas", precio: 15, categoria: "Salud y bienestar", marca: "Vitamin C", presentacion: "240 cápsulas", objetivos: ["Salud general"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "zinc-chelate-50mg-120-caps", nombre: "Zinc Chelate 50 mg 120 cápsulas", precio: 15, categoria: "Salud y bienestar", marca: "Zinc Chelate", presentacion: "120 cápsulas", objetivos: ["Belleza","Salud general"] }),
  product({ id: "primaforce-zma-180-capsulas-60-srv-women-90-srv-men", nombre: "ZMA  180 cápsulas", precio: 15, categoria: "Salud y bienestar", marca: "primaforce", presentacion: "60 srv women - 90 srv men", objetivos: ["Descanso y estrés","Recuperación"] }),
  product({ id: "zma-180-caps", nombre: "ZMA 180 cápsulas", precio: 22.5, categoria: "Salud y bienestar", marca: "ZMA", presentacion: "180 cápsulas", objetivos: ["Descanso y estrés","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "zma-90-caps", nombre: "ZMA 90 cápsulas", precio: 22, categoria: "Salud y bienestar", marca: "nutricost", presentacion: "30 servidas", objetivos: ["Descanso y estrés","Recuperación"] }),
  product({ id: "optimum-nutrition-creatine-60-serv", nombre: "Micronized Creatine 60 servidas", precio: 15.5, categoria: "Sin sabor", marca: "Optimum Nutrition", presentacion: "60 servidas", objetivos: ["Fuerza y rendimiento"], imagen: "img/products/optimum-nutrition-creatine-60-serv.webp" }),
  product({ id: "magnesium-complex-240-caps", nombre: "Magnesium Complex 240 cápsulas", precio: 20, categoria: "Sueño/estrés", marca: "Magnesium Complex", presentacion: "240 cápsulas", objetivos: ["Descanso y estrés"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "vitamin-e-30-caps", nombre: "Vitamin E", precio: 10.5, categoria: "Vitaminas", marca: "nutricost", presentacion: "30 cápsulas", objetivos: ["Belleza","Salud general"] }),
  product({ id: "nutrex-100-whey-protein", nombre: "100% Whey Protein", precio: 35, categoria: "Whey", marca: "Nutrex", presentacion: "2 lb - 27 servidas", sabores: ["Chocolate","Vainilla","Cookies and Cream"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/nutrex-100-whey-protein.webp" }),
  product({ id: "nutrabol-c4-whey-2lb", nombre: "C4 Whey Protein", precio: 38, categoria: "Whey", marca: "Cellucor", presentacion: "2.2 lb - 28 servidas", sabores: ["Hershey's"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/nutrabol-c4-whey-2lb.webp" }),
  product({ id: "nutrabol-c4-whey-5lb", nombre: "C4 Whey Protein", precio: 71, categoria: "Whey", marca: "Cellucor", presentacion: "5.8 lb - 66 servidas", sabores: ["Reese's Chocolate Peanut Butter"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/nutrabol-c4-whey-5lb.webp" }),
  product({ id: "optimum-nutrition-gold-standard-whey-5lb", nombre: "Gold Standard 100% Whey", precio: 75, categoria: "Whey", marca: "Optimum Nutrition", presentacion: "5 lb - 73 servidas", sabores: ["Chocolate","Vainilla","Strawberries and Cream"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/optimum-nutrition-gold-standard-whey-5lb.webp" }),
  product({ id: "optimun-nutrition-gold-standard-100-whey-protein-1-85-lb-27-servidas", nombre: "Gold Standard 100% Whey Protein", precio: 50, categoria: "Whey", marca: "Optimun  Nutrition", presentacion: "1.85 lb - 27 servidas", sabores: ["Fresa","Chocolate","Cookies","Vainilla"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "muscletech-nitro-tech-whey-gold-2lb", nombre: "MuscleTech Nitro-Tech Whey Gold 2 lb", precio: 40, categoria: "Whey", marca: "MuscleTech", presentacion: "2 lb", sabores: ["Cookies & Cream","Vainilla"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/muscletech-nitro-tech-whey-gold-2lb.webp" }),
  product({ id: "muscletech-nitro-tech-whey-gold-5lb", nombre: "Nitro Tech 100% Whey Gold", precio: 72, categoria: "Whey", marca: "MuscleTech", presentacion: "5 lb - 69 servidas", sabores: ["Double Rich Chocolate","Cookies"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/muscletech-nitro-tech-whey-gold-5lb.webp" }),
  product({ id: "muscletech-nitro-tech-whey-gold-gourtmet-5-lb-67-servidas", nombre: "Nitro Tech Whey Gold Gourtmet", precio: 80, categoria: "Whey", marca: "Muscletech", presentacion: "5 lb - 67 servidas", sabores: ["Double Rich Chocolate","Chocolate","Peanut Butter"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "nutricost-protein-1-5lb", nombre: "Nutricost Whey Protein Concentrate 1.5 lb", precio: 24, categoria: "Whey", marca: "Nutricost", presentacion: "1.5 lb", sabores: ["Chocolate","Vainilla"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/nutricost-protein-1-5lb.webp" }),
  product({ id: "prosupps-whey-premium-5lb", nombre: "Whey Concentrate Premium Protein 5 lb", precio: 63, categoria: "Whey", marca: "ProSupps", presentacion: "5 lb - 63 servidas", sabores: ["Vainilla","Galleta","Chocolate"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/prosupps-whey-premium-5lb.webp" }),
  product({ id: "mutant-whey-protein-5lb", nombre: "Whey Protein", precio: 50, categoria: "Whey", marca: "Mutant", presentacion: "5 lb - 61 servidas", sabores: ["Fresa","Triple Chocolate","Vainilla","Cookies"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
  product({ id: "nutrex-whey-protein-5-lb-67-servidas", nombre: "Whey Protein", precio: 55, categoria: "Whey", marca: "Nutrex", presentacion: "5 lb - 67 servidas", sabores: ["Vainilla","Cookies","Chocolate"], objetivos: ["Ganar masa","Recuperación"] }),
  product({ id: "xtreme-whey-5lb", nombre: "Xtreme Whey", precio: 55, categoria: "Whey", marca: "Biosport", presentacion: "5 lb - 70 servidas", sabores: ["Chocolate","Cookies"], objetivos: ["Ganar masa","Recuperación"], imagen: "img/products/product-placeholder.svg" }),
];

const PRODUCTS = Object.fromEntries(PRODUCT_LIST.map((item) => [item.id, item]));
